# **4.1 Exercise on Functions:**

Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2. Ask the user to input the value to be converted.

3. Perform the conversion and display the result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convertLength(value, from_unit):
  if from_unit == "m":
    return value * 3.28084
  elif from_unit == "ft":
    return value / 3.28084
  else:
    raise ValueError("Invalid unit")

def convertVolume(value, from_unit):
  if from_unit == "l":
    return value * 0.264172
  elif from_unit == "gal":
    return value * 0.264172
  else:
    raise ValueError("Invalid unit")

def convertWeight(value, from_unit):
  if from_unit == "kg":
    return value * 2.20462
  elif from_unit == "lbs":
    return value * 2.20462
  else:
    raise ValueError("Invalid unit")

def main():
    print(
    """
    Unit Converter: Choose a conversion type
    1. Length (m - ft)
    2. Weight (kg - lbs)
    3. Volume (l - gal)
    """
    )

    try:
        choice = int(input("Enter your choice: "))
        value = float(input("Enter value to be converted: "))

        if choice == 1:
            unit = input("Enter unit (m or ft): ")
            convertedValue = convertLength(value, unit)
            print(f"Converted value: {convertedValue:.2f}")
        elif choice == 2:
            unit = input("Enter unit (kg or lbs): ")
            convertedValue = convertWeight(value, unit)
            print(f"Converted value: {convertedValue:.2f}")
        elif choice == 3:
            unit = input("Enter unit (l or gal): ")
            convertedValue = convertVolume(value, unit)
            print(f"Converted value: {convertedValue:.2f}")
        else:
            print("Invalid choice. Please enter a number between 1 and 3.")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values and unit types.")

if __name__ == "__main__":
    main()


    Unit Converter: Choose a conversion type
    1. Length (m - ft)
    2. Weight (kg - lbs)
    3. Volume (l - gal)
    
Enter your choice: 3
Enter value to be converted: 45
Enter unit (l or gal): l
Converted value: 11.89


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
def calculateSum(num):
    return sum(num)

def calculateAverage(num):
    return sum(num) / len(num)

def findMaximum(num):
    return max(num)

def findMinimum(num):
    return min(num)

def main():
    print(
    """
    Mathematical Operations:
    1. Sum
    2. Average
    3. Maximum
    4. Minimum
    """
    )

    try:
        choice = int(input("Enter your choice: "))
        num = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

        if not num:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            print(f"Sum: {calculateSum(num)}")
        elif choice == 2:
            print(f"Average: {calculateSum(num):.2f}")
        elif choice == 3:
            print(f"Maximum: {findMaximum(num)}")
        elif choice == 4:
            print(f"Minimum: {findMinimum(num)}")
        else:
            print("Invalid choice. Please select a number between 1 and 4.")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values.")

if __name__ == "__main__":
    main()



    Mathematical Operations:
    1. Sum
    2. Average
    3. Maximum
    4. Minimum
    
Enter your choice: 1
Enter a list of numbers separated by spaces: 2 3 4 
Sum: 9.0


# **4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extractEveryOther(lst):
    return lst[::2]

lists = [1,2,3,4,5,6]
print(extractEveryOther(lists))


[1, 3, 5]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def getSublist(lst, start, end):
  return lst[start:end + 1]

lists = [1,2,3,4,5]
print(getSublist(lists, 2, 4))

[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

• Requirements:

- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverseList(lst):
  return lst[::-1]

lists = [1,2,3,4,5]
print(reverseList(lists))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def removeFirstLast(lst):
  return lst[1:-1]

lists = [4,5,6,7,8,9]
print(removeFirstLast(lists))

[5, 6, 7, 8]


**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

• Requirements:

- Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def getFirstN(lst,n):
  return lst[:n]

lists = [4,5,6,7,8]
print(getFirstN(lists,3))

[4, 5, 6]


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def getLastN(lst, n):
  return lst[-n:]

lists = [1,2,3,4,5]
print(getLastN(lists, 2))

[4, 5]


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

 Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverseSkip(lst):
  return lst[-2::-2]

li = [2,3,4,5,6,7]
print(reverseSkip(li))

[6, 4, 2]


# **4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  result = []
  for sublist in lst:
    try:
      result.extend(flatten(sublist))
    except TypeError:
      result.append(sublist)
  return result

li = [[1,2],[3,4],[5,6]]
flatten = flatten(li)
print(flatten)

[1, 2, 3, 4, 5, 6]


**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def accessNestedElement(lst, indices):
  for index in indices:
    lst = lst[index]
  return lst

lst = [[1,2,3],[4,5,6],[7,8,9]]
indices = [1,2]
elements = accessNestedElement(lst,indices)
print(elements)

6


**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

- Example: For the input [[1, 2], [3,[4, 5]], 6], the output should be 21.

In [ ]:
def sumNested(lst):
  total = 0
  for item in lst:
    if isinstance(item,list):
      total+=sumNested(item)
    else:
       total+=item
  return total

lst= [[1,2],[3,[4,5]],6]
total = sumNested(lst)
print(total)

21


**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [ ]:
def removeElement(lst,elem):
  for i in range(len(lst)):
      lst[i] = [x for x in lst[i] if x != elem]

  return [sublist for sublist in lst if sublist]

lst =[[1,2],[3,2],[4,5]]
elem=2
modifiedLst = removeElement(lst,elem)
print(modifiedLst)

[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

- Define a function find max(lst) that takes a nested list lst and returns the maximum element.

- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def findMax(lst):
  max_value = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_value = max(max_value, findMax(item))
    else:
      max_value = max(max_value, item)
  return max_value

lists = [[4,5],[6,[7,8]],9]
max_value = findMax(lists)
print(max_value)

9


**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def countOccurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += countOccurrences(item, elem)
    elif item == elem:
      count += 1
  return count

lst=[[1,2],[2,3],[3,4],[4,3]]
occurrence = countOccurrences(lst,3)
print(occurrence)

3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deepFlatten(lst):
  result = []
  for item in lst:
    if isinstance(item, list):
      result.extend(deepFlatten(item))
    else:
      result.append(item)
  return result

lst=[[[1,2],[3,4]],[[5,6],[7,8]]]
flatten = deepFlatten(lst)
print(flatten)

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def averagNested(lst):
  def sum(lst):
    total=0
    count=0
    for item in lst:
      if isinstance(item,list):
        sumTotal, subCount = sum(item)
        total+=sumTotal
        count+=subCount
      else:
        total+=item
        count+=1

    return total,count

  total, count = sum(lst)
  return total/count if count != 0 else 0

lst= [[1, 2], [3, 4], [5, 6]]
ave = averagNested(lst)
print(ave)

3.5


# **10.1. Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [3]:
import numpy as np

empty_array= np.empty((2,2))
print("Empty Array (2x2):\n",empty_array)

ones_array= np.ones((4,2))
print("\n")
print("Ones Array (4x2):\n",ones_array)

newArray = np.full((3,3),5)
print("\n")
print("Filled Array (with 5):\n",newArray)

array= np.array([[2,2],[4,2]])
zerosArray = np.zeros_like(array)
print("\n")
print("Zeros Array:\n",zerosArray)

onesArray = np.ones_like(array)
print("\n")
print("Ones Array:\n",onesArray)

new_list = [1,2,3,4]
numpyArray = np.array(new_list)
print("\n")
print("Numpy Array:\n",numpyArray)

Empty Array (2x2):
 [[3.09983634e-316 0.00000000e+000]
 [6.65840300e-310 6.65840343e-310]]


Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Filled Array (with 5):
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


Zeros Array:
 [[0 0]
 [0 0]]


Ones Array:
 [[1 1]
 [1 1]]


Numpy Array:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [6]:
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix_3x3)

identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nMean of Random Array (size 30):", mean_value)

random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n10x10 Random Matrix - Min:", min_value, "Max:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array (size 30): 0.45948296800470995

10x10 Random Matrix - Min: 0.0017871312013630902 Max: 0.9927689923653433

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [7]:
# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("Addition of x and y:\n", add_xy)

subtract_xy = x - y
print("\nSubtraction of x and y:\n", subtract_xy)

multiply_x = x * 2
print("\nMultiplication of x with 2:\n", multiply_x)

square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot Product of v and w:", dot_vw)
print("Dot Product of x and v:\n", dot_xv)
print("Dot Product of x and y:\n", dot_xy)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))

print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot Product of v and w: 219
Dot Product of x and v:
 [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [8]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:")
print(identity_matrix)

# Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB ≠ BA?", not np.array_equal(AB, BA))

# Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(BT_AT)
print("Does (AB)^T = B^T * A^T?", np.array_equal(AB_T, BT_AT))

# Solve the system of linear equations using Inverse Method
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using A^-1 * B
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution for the system of equations:")
print(X)


A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB ≠ BA? True
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Does (AB)^T = B^T * A^T? True
Solution for the system of equations:
[ 2.  1. -2.]


# **10.2 Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [10]:
import time
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
python_add_time = time.time() - start_time

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_addition = array1 + array2
numpy_add_time = time.time() - start_time

**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [11]:
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
python_mul_time = time.time() - start_time

start_time = time.time()
array_multiplication = array1 * array2
numpy_mul_time = time.time() - start_time

**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [12]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
python_dot_time = time.time() - start_time

start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
numpy_dot_time = time.time() - start_time

**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [13]:
size_matrix = 1000
matrix1_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)
matrix2_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)

start_time = time.time()
matrix_multiplication_np = np.dot(matrix1_np, matrix2_np)
numpy_matrix_time = time.time() - start_time

In [14]:
print(f"Python Addition Time: {python_add_time:.5f} seconds")
print(f"NumPy Addition Time: {numpy_add_time:.5f} seconds")
print(f"Python Multiplication Time: {python_mul_time:.5f} seconds")
print(f"NumPy Multiplication Time: {numpy_mul_time:.5f} seconds")
print(f"Python Dot Product Time: {python_dot_time:.5f} seconds")
print(f"NumPy Dot Product Time: {numpy_dot_time:.5f} seconds")
print(f"NumPy Matrix Multiplication Time: {numpy_matrix_time:.5f} seconds")

Python Addition Time: 0.18066 seconds
NumPy Addition Time: 0.00509 seconds
Python Multiplication Time: 0.10616 seconds
NumPy Multiplication Time: 0.00277 seconds
Python Dot Product Time: 0.17289 seconds
NumPy Dot Product Time: 0.00216 seconds
NumPy Matrix Multiplication Time: 1.74621 seconds
